### ISSUE TITLE
Error at executing namebench from menu or from console in home folder

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jeevandongre/namebench#102]
```
I have installed namebench 1.2Beta1 with "sudo python setup.py install" in
Ubuntu Karmic 32 bits.

I execute namebench from menu and it does nothing.
I execute namebench.py from console (in home folder) and it shows this errors:
Traceback (most recent call last):
  File "/usr/local/bin/namebench.py", line 44, in <module>
    (options, supplied_ns, global_ns, regional_ns) = config.GetConfiguration()
  File "/usr/local/lib/python2.6/dist-packages/libnamebench/config.py",
line 38, in GetConfiguration
    (configured_options, global_ns, regional_ns) =
ProcessConfigurationFile(options)
  File "/usr/local/lib/python2.6/dist-packages/libnamebench/config.py",
line 147, in ProcessConfigurationFile
    general = dict(config.items('general'))
  File "/usr/lib/python2.6/ConfigParser.py", line 564, in items
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'general'

I execute namebench.py from console (in folder where I have the namebench
sources) and it works ok... ¿?

```

Original issue reported on code.google.com by `simon@simonbcn.net` on 26 Feb 2010 at 12:30

**Comment by GoogleCodeExporter** [comment]
```
I think this has been fixed in revision 684 (and possibly earlier). The next 
beta
should not have this issue.

```

Original comment by `tstromb...@google.com` on 26 Feb 2010 at 5:01
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
Original comment by `tstromb...@google.com` on 2 Mar 2010 at 2:09
- Changed state: **Fixed**
