### ISSUE TITLE
Error running: TypeError: __init__() takes at least 4 arguments 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jeevandongre/namebench#119]
```
What steps will reproduce the problem?
1. Run namebench-1.2-Windows.exe
2. Wait until extraction
3. Error occurs

What is the expected output? What do you see instead?
I see the following error:
"Errors occurred"
"See logfile 'C:\DOCUME~1\<username>\CONFIG~1\Temp\namebench.exe.log'" for
details.

What version of the product are you using? On what operating system?
namebench 1.2 for Windows (portable self-extracting executable)

Please provide any additional information below.

Contents of the log file:
-----
Traceback (most recent call last):
  File "namebench.py", line 78, in <module>
  File "libnamebench\tk.pyc", line 139, in Execute
  File "libnamebench\tk.pyc", line 242, in DrawWindow
TypeError: __init__() takes at least 4 arguments (3 given)
-----

Windows dependencies installed:
vcredist_x86.exe - Microsoft Visual C++ 2008 SP1 Redistributable Package (x86)

Other comments:
Version 1.1 works as expected.
```

Original issue reported on code.google.com by `daesir_...@yahoo.es` on 11 May 2010 at 3:19

**Comment by GoogleCodeExporter** [comment]
```
I suggest changing the name of the issue to "1.2 windows: init takes at least 4
arguments (3 given)" or something like that.

```

Original comment by `daesir_...@yahoo.es` on 11 May 2010 at 6:50

**Comment by GoogleCodeExporter** [comment]
```
The culprit line is:

data_source = OptionMenu(inner_frame, self.data_source, *source_titles)

Honestly, I'm not sure how this could cause an error for some peoples machines. 
I looked at the Python 2.6 
docs, and it seems that things have changed, and there is an additional option 
now:


__init__(self, master, variable, value, *values, **kwargs)

value being the initial value. For some reason, this initial value does not 
appear to actually do anything. I 
wonder if this is more due to only finding one source of history to use. 
Unusual.

```

Original comment by `helixblue` on 16 May 2010 at 10:33

**Comment by GoogleCodeExporter** [comment]
```
This doesn't seem limited to Windows as I see the same problem on a Debian 
testing
machine:

shodan:~$ namebench 
Starting Tk interface for namebench...
> Ignoring /usr/share/namebench/data/alexa-top-10000-global.txt from alexa (78 
days old)
> Ignoring /home/steltek/.kde/share/apps/konqueror/konq_history (only 509 bytes)
Traceback (most recent call last):
  File "/usr/bin/namebench", line 78, in <module>
    namebench.Execute()
  File "/usr/lib/pymodules/python2.5/libnamebench/tk.py", line 139, in Execute
    app.DrawWindow()
  File "/usr/lib/pymodules/python2.5/libnamebench/tk.py", line 242, in DrawWindow
    data_source = OptionMenu(inner_frame, self.data_source, *source_titles)
TypeError: __init__() takes at least 4 arguments (3 given)


python-tk is Version: 2.6.5-1 / Source: python-stdlib-extensions


```

Original comment by `lev.ar...@gmail.com` on 17 May 2010 at 2:34

**Comment by GoogleCodeExporter** [comment]
```
After some more debugging, I've discovered that this is the same as issue 122 - 
but the side effect is different on 
the Tk version of the UI. In a nutshell, namebench isn't able to find any 
browser history files, and is unable to 
fallback to the Alexa dataset due to issue 116.

A fix for this is forthcoming. It's still surprising to me that it is unable to 
find a browser history for Windows 
users. If you are running namebench from a machine where you are also using a 
web browser, if you could 
provide a  namebench .log file (or console output), it would be greatly 
appreciated.

```

Original comment by `helixblue` on 17 May 2010 at 3:09
- Changed title: *_Error running: TypeError: **init**() takes at least 4 arguments *_

**Comment by GoogleCodeExporter** [comment]
```
Can you try the newly released namebench 1.3-BETA1 to see if it resolves this 
bug?
```

Original comment by `helixblue` on 20 May 2010 at 3:20

**Comment by GoogleCodeExporter** [comment]
```
I tried the new namebench 3.1 beta 1, and despite taking some time for starting 
(the
main window takes like 1 minute to appear), it opens correctly.
```

Original comment by `daesir_...@yahoo.es` on 20 May 2010 at 6:55

**Comment by GoogleCodeExporter** [comment]
```
Thanks!
```

Original comment by `helixblue` on 20 May 2010 at 11:25
- Changed state: **Verified**
