### ISSUE TITLE
"Argument of type 'bool' is not iterable"

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jeevandongre/namebench#129]
```
What steps will reproduce the problem?
1. Launch namebench
2. Write more than one nameservers, comma-separated
3. Start benchmark

What is the expected output? What do you see instead?
XML file

What version of the product are you using? On what operating system?
Error at the end: "Argument of type bool is not iterable"

Please provide any additional information below.

Here the log file:

Traceback (most recent call last):
  File "libnamebench\tk.pyc", line 120, in run
  File "libnamebench\base_ui.pyc", line 154, in RunAndOpenReports
  File "libnamebench\base_ui.pyc", line 200, in CreateReports
  File "libnamebench\reporter.pyc", line 196, in CreateReport
  File "libnamebench\reporter.pyc", line 321, in _GenerateNameServerSummary
  File "libnamebench\url_map.pyc", line 39, in CreateNoteUrlTuples
  File "libnamebench\url_map.pyc", line 31, in GetUrlForNote
TypeError: argument of type 'bool' is not iterable
Traceback (most recent call last):
  File "libnamebench\tk.pyc", line 120, in run
  File "libnamebench\base_ui.pyc", line 154, in RunAndOpenReports
  File "libnamebench\base_ui.pyc", line 200, in CreateReports
  File "libnamebench\reporter.pyc", line 196, in CreateReport
  File "libnamebench\reporter.pyc", line 321, in _GenerateNameServerSummary
  File "libnamebench\url_map.pyc", line 39, in CreateNoteUrlTuples
  File "libnamebench\url_map.pyc", line 31, in GetUrlForNote
TypeError: argument of type 'bool' is not iterable


```

Original issue reported on code.google.com by `subvert...@gmail.com` on 5 Jun 2010 at 10:27

**Comment by GoogleCodeExporter** [comment]
```
I'm using Win7 x32
```

Original comment by `subvert...@gmail.com` on 5 Jun 2010 at 10:28

**Comment by GoogleCodeExporter** [comment]
```
Thanks - I have not seen this bug yet. Somehow, a note of True/False is being 
stored, rather than a string. Very 
strange. Is this crash repeatable?

```

Original comment by `helixblue` on 5 Jun 2010 at 10:38

**Comment by GoogleCodeExporter** [comment]
```
The issues is reproducible. It seems that it happens when the nameserver list 
containt 
at least 1 healthy server and at least 1 non-healthy server.

For me always with this input: 8.8.8.8, 62.101.93.101

To speedup untick "include global dns providers" and "include best regional..." 
and set  
queries to 10. This does not change the behavior.
```

Original comment by `subvert...@gmail.com` on 5 Jun 2010 at 11:13

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the bug report and screenshot. I think I have fixed the bug in r983  
- can you download 1.3.1-RC1 to 
see if it works properly for you?

http://namebench.googlecode.com/files/namebench-1.3.1-RC1-Windows.exe

Thanks!
```

Original comment by `helixblue` on 5 Jun 2010 at 5:04
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
Issue 131 has been merged into this issue.
```

Original comment by `helixblue` on 5 Jun 2010 at 6:08

**Comment by GoogleCodeExporter** [comment]
```
I've now posted 1.3.1-RC2 which should fix this issue - 
http://code.google.com/p/namebench/downloads/list - 
please let me know how it works for you.

```

Original comment by `helixblue` on 5 Jun 2010 at 6:20

**Comment by GoogleCodeExporter** [comment]
```
Still failing, but with a different error.  See attached.
```

Original comment by `gene.spa...@gmail.com` on 5 Jun 2010 at 6:55

Attachments:
- [Screen shot 2010-06-05 at 2.53.56 PM.PNG](https://storage.googleapis.com/google-code-attachments/namebench/issue-129/comment-7/Screen shot 2010-06-05 at 2.53.56 PM.PNG)

**Comment by GoogleCodeExporter** [comment]
```
This issue was closed by revision r990.
```

Original comment by `thomas.r...@gmail.com` on 5 Jun 2010 at 7:52
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Based on your bug reports, I was able to finally nail down the core of the 
issue. It was a change of API that I 
didn't change everywhere. In the case of a DNS server that we were not able to 
do cache-sharing checks on. Try 
1.3.1-RC3:

http://code.google.com/p/namebench/downloads/list

```

Original comment by `helixblue` on 5 Jun 2010 at 8:59

**Comment by GoogleCodeExporter** [comment]
```
Yes, that seems to have fixed it -- thanks.
```

Original comment by `gene.spa...@gmail.com` on 5 Jun 2010 at 11:00
