### ISSUE TITLE
Error message while creating report

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jeevandongre/namebench#148]
```
What steps will reproduce the problem?
Run Namebench
press "Start benchmark"

What is the expected output? What do you see instead?
While creating the report I see only a error message with the following entries 
(copied from the logfile). No report is then created
---------------------------------------------
Traceback (most recent call last):
  File "libnamebench\tk.pyc", line 120, in run
  File "libnamebench\base_ui.pyc", line 154, in RunAndOpenReports
  File "libnamebench\base_ui.pyc", line 200, in CreateReports
  File "libnamebench\reporter.pyc", line 259, in CreateReport
  File "nb_third_party\jinja2\environment.pyc", line 868, in render
  File "H:\nb\namebench\templates\html.tmpl", line 75, in top-level template code
UnicodeDecodeError: 'ascii' codec can't decode byte 0xfc in position 126: 
ordinal not in range(128)

---------------------------------------

What version of the product are you using? On what operating system?
Latest Version 1.3.1 Windows 7 32bit German
I got the same error with Version 1.3 of namebench. Namebench 1.2 is running 
fine without this problem.

Please provide any additional information below.
Thanks for a great tool!

```

Original issue reported on code.google.com by `lutzp...@googlemail.com` on 27 Jun 2010 at 8:56

**Comment by GoogleCodeExporter** [comment]
```
similar issue here (twice)
Turkish Windows XP SP3

1st: anonymous upload on...
Traceback (most recent call last):
  File "libnamebench\tk.pyc", line 120, in run
  File "libnamebench\base_ui.pyc", line 154, in RunAndOpenReports
  File "libnamebench\base_ui.pyc", line 179, in CreateReports
  File "libnamebench\reporter.pyc", line 422, in CreateJsonData
  File "nb_third_party\simplejson\__init__.pyc", line 261, in dumps
  File "nb_third_party\simplejson\encoder.pyc", line 216, in encode
  File "nb_third_party\simplejson\encoder.pyc", line 485, in _iterencode
  File "nb_third_party\simplejson\encoder.pyc", line 459, in _iterencode_dict
  File "nb_third_party\simplejson\encoder.pyc", line 380, in _iterencode_list
  File "nb_third_party\simplejson\encoder.pyc", line 459, in _iterencode_dict
  File "nb_third_party\simplejson\encoder.pyc", line 380, in _iterencode_list
  File "nb_third_party\simplejson\encoder.pyc", line 439, in _iterencode_dict
  File "nb_third_party\simplejson\encoder.pyc", line 50, in py_encode_basestring_ascii
  File "encodings\utf_8.pyc", line 16, in decode
UnicodeDecodeError: 'utf8' codec can't decode bytes in position 76-77: invalid 
data

2nd: anonymous upload off...
Traceback (most recent call last):
  File "libnamebench\tk.pyc", line 60, in AddMsg
  File "Tkinter.pyc", line 1378, in event_generate
TclError: expected boolean value but got "??"
Traceback (most recent call last):
  File "libnamebench\tk.pyc", line 120, in run
  File "libnamebench\base_ui.pyc", line 154, in RunAndOpenReports
  File "libnamebench\base_ui.pyc", line 200, in CreateReports
  File "libnamebench\reporter.pyc", line 259, in CreateReport
  File "nb_third_party\jinja2\environment.pyc", line 868, in render
  File "C:\DOCUME~1\OEM\LOCALS~1\Temp\namebench\templates\html.tmpl", line 75, in top-level template code
UnicodeDecodeError: 'ascii' codec can't decode byte 0xdd in position 76: 
ordinal not in range(128)

```

Original comment by `ozzymanb...@gmail.com` on 30 Oct 2010 at 8:42

**Comment by GoogleCodeExporter** [comment]
```
It has almost been a year and yet they haven't fixed the issue. Talk about lazy 
workers.
```

Original comment by `AsdaOnl...@gmail.com` on 12 Mar 2011 at 9:16

**Comment by GoogleCodeExporter** [comment]
```
Same error here, on Debian Squeeze x86.
```

Original comment by `strash...@gmail.com` on 21 Sep 2012 at 8:56

**Comment by GoogleCodeExporter** [comment]
```
Hello
Same error on XP-SP3
ascii codec can't decode byte oxe9 in position 92: ordinal not in range (128)
Warmly
```

Original comment by `efede...@gmail.com` on 14 Feb 2014 at 7:46

**Comment by GoogleCodeExporter** [comment]
```
If you get the same error just replace both adress in the nameserver line with 
your actually used dns server adress(if unknown use your routers ip only) or 
delete at least the empty one(0.0.0.0). Then it should work. You have to do it 
every time you start the programm. Viel Glück!

Annemarie
```

Original comment by `watislos...@freenet.de` on 28 May 2014 at 5:45

Attachments:
- [start screen.jpg](https://storage.googleapis.com/google-code-attachments/namebench/issue-148/comment-5/start screen.jpg)
