### ISSUE TITLE
global name 'exc' is not defined

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jeevandongre/namebench#154]
```
What steps will reproduce the problem?
1. Install Namebench
2. open terminal and type namebench.py
3.

What is the expected output? What do you see instead?

runs but with errors

What version of the product are you using? On what operating system?

1.1 on Ubuntu 10 Lucid

Please provide any additional information below.

Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/libnamebench/tk.py", line 102, in run
    self.PrepareNameServers()
  File "/usr/local/lib/python2.6/dist-packages/libnamebench/base_ui.py", line 74, in PrepareNameServers
    (primary_checks, secondary_checks, censor_tests) = config.GetLatestSanityChecks()
  File "/usr/local/lib/python2.6/dist-packages/libnamebench/config.py", line 101, in GetLatestSanityChecks
    except exc:
NameError: global name 'exc' is not defined
Showing popup: global name 'exc' is not defined
> global name 'exc' is not defined

```

Original issue reported on code.google.com by `ubuntup...@gmail.com` on 12 Jul 2010 at 3:23
- Merged into: #93

**Comment by GoogleCodeExporter** [comment]
```
Feel free to open a bug with the Ubuntu folks on this one. The current version 
of namebench is 1.3.1 (where the bug has been long fixed).

```

Original comment by `helixblue` on 12 Jul 2010 at 5:15
- Changed state: **Duplicate**
