### ISSUE TITLE
Mac OS X: Cocoa UI doesn't run on PPC (Tk and CLI versions do)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jeevandongre/namebench#20]
```
0.9.1.1 doesn't launch on PPC/Leopard, as it's only built for Intel. I couldn't 
get a PPC built version to run on my own, but I've never built a Cocoa-Python 
app before.
```

Original issue reported on code.google.com by `jon%jons...@gtempaccount.com` on 15 Oct 2009 at 3:29

**Comment by GoogleCodeExporter** [comment]
```
Also, the python script itself fails to run on this machine. Fails with this 
message: 
namebench-0.9.1/namebench.pyTraceback (most recent call last):
  File "namebench-0.9.1/namebench.py", line 133, in <module>
    (options, primary, secondary) = config.GetConfiguration()
  File "namebench-0.9.1/lib/config.py", line 26, in GetConfiguration
    (configured_options, primary, secondary) = ProcessConfigurationFile(options)
  File "namebench-0.9.1/lib/config.py", line 92, in ProcessConfigurationFile
    general = dict(config.items('general'))
  File 
"/System/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/Config
Parser.py", line 544, in items
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'general'
```

Original comment by `jon%jons...@gtempaccount.com` on 15 Oct 2009 at 5:11

**Comment by GoogleCodeExporter** [comment]
```
Sorry about the lack of a PPC version. The project should build cleanly if you 
open it with XCode. For some 
reason XCode 3.2/10.6 isn't giving me the option of building a PPC version, but 
I remember seeing it available 
on another machine. I will see about creating a build for it.

namebench.py should work from the command-line, but it does make an assumption 
that you are running it 
from the directory where namebench.cfg is located.


```

Original comment by `helixblue` on 16 Oct 2009 at 9:26

**Comment by GoogleCodeExporter** [comment]
```
Ah, quite right about the script itself. 

Like I said, I can build the Mac GUI using Xcode 3.1.4 on Leopard, but it fails 
on 
lauch with this message: 

namebench[66778:10b] Resource directory is /Programming/namebench-read-
only/cocoa/build/Debug/namebench.app/Contents/Resources
Traceback (most recent call last):
  File "/Users/jshier/Programming/namebench-read-
only/cocoa/build/Debug/namebench.app/Contents/Resources/main.py", line 18, in 
<module>
    import controller
  File "/Users/jshier/Programming/namebench-read-
only/cocoa/build/Debug/namebench.app/Contents/Resources/controller.py", line 
32, in <module>
    from lib import config
ImportError: No module named lib
2009-10-16 07:58:28.691 namebench[66778:10b] *** Terminating app due to 
uncaught exception 'NSInternalInconsistencyException', reason: 
'/Programming/namebench-read-only/cocoa/main.m:44 main() PyRun_SimpleFile 
failed with file '/Programming/namebench-read-
only/cocoa/build/Debug/namebench.app/Contents/Resources/main.py'.  See 
console for errors.'
2009-10-16 07:58:28.691 namebench[66778:10b] Stack: (
    2528972016,
    2520847596,
    2528971776,
    2528971832,
    11488,
    10136
)
```

Original comment by `jon%jons...@gtempaccount.com` on 16 Oct 2009 at 11:59

**Comment by GoogleCodeExporter** [comment]
```
Mind trying it again? 0.9.3 should behave better with regards to this. Still no 
support for cross-platform 
compiles however =(

```

Original comment by `helixblue` on 16 Nov 2009 at 12:33

**Comment by GoogleCodeExporter** [comment]
Original comment by `tstromb...@google.com` on 8 Dec 2009 at 7:42
- Added labels: **Priority-Low**

**Comment by GoogleCodeExporter** [comment]
```
Added workaround in http://code.google.com/p/namebench/wiki/FAQ

Due to to the dependency on PyObjC, namebench requires an Intel Mac running Mac 
OS X 10.5 or higher. If you do not meet this requirement, you can still use 
namebench with the command-line or with a slightly ugly U I by downloading the 
"source" version of namebench.

Once extracted, you may run the following from the namebench directory to force 
a 
GUI to open:

I_LOVE_TK=1 ./namebench.py

```

Original comment by `thomas.r...@gmail.com` on 8 Dec 2009 at 5:54
- Changed title: **Mac OS X: Cocoa UI doesn't run on PPC (Tk and CLI versions do)**
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
Issue 72 has been merged into this issue.
```

Original comment by `thomas.r...@gmail.com` on 16 Dec 2009 at 8:45

**Comment by GoogleCodeExporter** [comment]
```
I got it to build and run on PPC. I had an odd experience doing this, for some 
reason the "third_party", 
"libnamebench", "tools" and "namebench.cfg" did not copy to the build file, but 
I just dragged a copy in by 
hand.

Anyways, I think the key difference is in changing your SDK to 10.5, not 10.6.

Here is what I customized:

ARCHS = $(ARCHS_STANDARD_32_64_BIT)
SDKROOT = macosx10.5
GCC_VERSION = 4.2

```

Original comment by `DreadLor...@gmail.com` on 17 Dec 2009 at 5:48

**Comment by GoogleCodeExporter** [comment]
```
I added in the folders (as references) and the config file with the above 
settings and now it works just fine on my 
10.5 PPC laptop.
```

Original comment by `DreadLor...@gmail.com` on 17 Dec 2009 at 6:44

**Comment by GoogleCodeExporter** [comment]
```
Here is an updated project file. Drag it in to replace the one in 
namebench/cocoa.
```

Original comment by `DreadLor...@gmail.com` on 20 Dec 2009 at 10:10

Attachments:
- [namebench.xcodeproj.zip](https://storage.googleapis.com/google-code-attachments/namebench/issue-20/comment-10/namebench.xcodeproj.zip)

**Comment by GoogleCodeExporter** [comment]
```
O.K. I get the let's spend more for new equipment but when your on a fixed 
income and
are not a programmer, what are you supposed to do? By the way there must be 
many of
us PPC users still out there!
```

Original comment by `nrow...@roadrunner.com` on 30 Dec 2009 at 1:34

**Comment by GoogleCodeExporter** [comment]
```
You don't need a PPC machine to compile PPC code just as you don't need an 
Intel machine to compile Intel code. 
The whole issue here is that the compile is not configured correctly. All one 
needs to do is set the architecture to 
universal binary and you are fine.
```

Original comment by `DreadLor...@gmail.com` on 31 Dec 2009 at 3:31

**Comment by GoogleCodeExporter** [comment]
```
Thanks to DreadLord.CyberSkull - namebench 1.1 beta 1 is now a universal 
binary. Can 
someone with PPC verify that it now works? Here is the download link:

http://namebench.googlecode.com/files/namebench-1.1b1.dmg

DreadLord also cleaned up the way the resources were assembled. You have my 
gratitude for your work.

```

Original comment by `thomas.r...@gmail.com` on 3 Jan 2010 at 11:01
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
Ran 1.1 with default settings, works fine.
```

Original comment by `DreadLor...@gmail.com` on 3 Jan 2010 at 11:37

**Comment by GoogleCodeExporter** [comment]
Original comment by `thomas.r...@gmail.com` on 26 Jan 2010 at 8:50
- Changed state: **Fixed**
