### ISSUE TITLE
Windows version running locally will not save .csv data ( not responding.... )

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jeevandongre/namebench#27]
```
What steps will reproduce the problem?
1.
2.
3.

What is the expected output? What do you see instead?


What version of the product are you using? On what operating system?


Please provide any additional information below.


```

Original issue reported on code.google.com by `stede.ga...@gmail.com` on 3 Dec 2009 at 6:55

**Comment by GoogleCodeExporter** [comment]
```
Having same issue.
OS is Windows Vista Ultimate x64
The problem is easy to reproduce, it happens with the default settings.

Nameservers 192.168.0.1
Include global DNS providers checked
Include best available regional DNS services checked
Benchmark data source: Firefox (1732)
Benchmark data selection: Weighted
Number of tests: 125
Numbers of runs: 1

Here's the contents of the log:

Traceback (most recent call last):
  File "libnamebench\tk.pyc", line 57, in run
  File "libnamebench\base_ui.pyc", line 92, in RunBenchmark
  File "libnamebench\base_ui.pyc", line 103, in CreateReports
  File "libnamebench\benchmark.pyc", line 299, in CreateReport
  File "third_party\jinja2\environment.pyc", line 669, in render
  File "C:\Users\polobunny\Desktop\ckz_N3ST\namebench\templates\html.tmpl", line 54,
in top-level template code
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 4: ordinal 
not
in range(128)
```

Original comment by `polobu...@gmail.com` on 3 Dec 2009 at 7:15

**Comment by GoogleCodeExporter** [comment]
```
Issue 28 has been merged into this issue.
```

Original comment by `tstromb...@google.com` on 4 Dec 2009 at 4:40

**Comment by GoogleCodeExporter** [comment]
```
Same issue on Windows 7 Ultimate x64 - with default settings or when adding 
extra 
ISP DNS. Program seems to function until it gets to Saving Query Details (CSV) 
and 
stops responding. Doesn't time out, even after several minutes-just hangs until 
killed.
```

Original comment by `colmobro...@gmail.com` on 4 Dec 2009 at 7:12

**Comment by GoogleCodeExporter** [comment]
```
Same issue of hanging and not responding when writing csv file on XP Sp3
```

Original comment by `blake.ga...@gmail.com` on 4 Dec 2009 at 8:48

**Comment by GoogleCodeExporter** [comment]
```
Do you mind trying 1.0 and seeing if it shows the same issue?

```

Original comment by `tstromb...@google.com` on 5 Dec 2009 at 12:58

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
namebench-1.0.exe
Same issue - hanging at Saving query details CSV.

Windows 7 Ultimate - default settings

Nameservers 24.116.2.50, 24.116.2.34
Include global DNS providers checked
Include best available regional DNS services checked
Benchmark data source: Firefox (2057)
Benchmark data selection: Weighted
Number of tests: 200
Numbers of runs: 1

Program seems to run fine until the writing csv file. 

Also, the unzipper works fine and produces the namebench program, however the 
unzipper hangs in the background by itself after producing the program and 
requiring 
manual closing. Unsure if this is related to this issue, or another entirely.

___________

Added: Same issue with attempting to use only 10 tests. Got to Rendering html: 
picture included.


```

Original comment by `placeboh...@gmail.com` on 5 Dec 2009 at 2:38

Attachments:
- [namebnech.png](https://storage.googleapis.com/google-code-attachments/namebench/issue-27/comment-7/namebnech.png)

**Comment by GoogleCodeExporter** [comment]
```
Exact same results on 1.0 - hanging at Saving Query Details CSV.

Windows 7 Ultimate 32 bit, default settings.  Also same problem with the 
unzipper - 
never closes.
```

Original comment by `mkertz...@gmail.com` on 5 Dec 2009 at 4:45

**Comment by GoogleCodeExporter** [comment]
```
Opened the unzipper issue as http://code.google.com/p/namebench/issues/detail?
id=30 - still investigating the saving query details csv issue. I haven't been 
able to 
replicate the hang yet in XP or Windows 7. I have seen this part perform poorly 
though. 
```

Original comment by `tstromb...@google.com` on 5 Dec 2009 at 7:34

**Comment by GoogleCodeExporter** [comment]
```
Version 1.0 seems to solve the problem for me.
```

Original comment by `thi.saa...@gmail.com` on 5 Dec 2009 at 4:14

**Comment by GoogleCodeExporter** [comment]
```
Running Windows XP SP3.  namebench-1.0.exe hangs similarly to what others above 
have 
said.  The last thing shown in the bottom of the namebench window talks about 
saving 
a CSV file, but nothing else happens and the program doesn't respond to 
anything.

With a little searching, I found that a CSV file was in fact created in Local 
Settings\Temp.  There's an HTML file with it, and these files appear to be 
correct 
and complete.

In addition, there's a directory with a constructed name like "ckz_A2LU" in 
Local 
Settings\Temp, which has a log file namebench.exe.log.  The contents of the log 
file 
are:

Traceback (most recent call last):
  File "libnamebench\tk.pyc", line 57, in run
  File "libnamebench\base_ui.pyc", line 93, in RunBenchmark
  File "libnamebench\base_ui.pyc", line 112, in DisplayHtmlReport
  File "libnamebench\better_webbrowser.pyc", line 40, in open
  File "libnamebench\better_webbrowser.pyc", line 45, in win32_open
  File "libnamebench\better_webbrowser.pyc", line 63, in create_win32_http_cmd
  File "libnamebench\better_webbrowser.pyc", line 52, in get_win32_http_handler
WindowsError: [Error 2] The system cannot find the file specified

Hope this information helps...
```

Original comment by `ericback...@gmail.com` on 5 Dec 2009 at 8:33

**Comment by GoogleCodeExporter** [comment]
```
Thanks Eric! That information helps quite a bit. Could you attach the logfile 
to this page? If it's possible, could 
you tell me what the registry entry for 
HKEY_CURRENT_USER\Software\Classes\http\shell\open\command 
shows? Otherwise, if you could tell me what your default web browser (including 
version) is, I might be able to 
replicate the situation here.

Thanks for getting to the bottom of it.

```

Original comment by `helixblue` on 6 Dec 2009 at 3:24

**Comment by GoogleCodeExporter** [comment]
```
Same issue of hanging and not responding when writing csv file on Windows 7 
Professional.
```

Original comment by `ronkov...@gmail.com` on 7 Dec 2009 at 12:50

**Comment by GoogleCodeExporter** [comment]
```
helixblue: The entire contents of the logfile is what I gave above.  Here it is 
again:

Traceback (most recent call last):
  File "libnamebench\tk.pyc", line 57, in run
  File "libnamebench\base_ui.pyc", line 93, in RunBenchmark
  File "libnamebench\base_ui.pyc", line 112, in DisplayHtmlReport
  File "libnamebench\better_webbrowser.pyc", line 40, in open
  File "libnamebench\better_webbrowser.pyc", line 45, in win32_open
  File "libnamebench\better_webbrowser.pyc", line 63, in create_win32_http_cmd
  File "libnamebench\better_webbrowser.pyc", line 52, in get_win32_http_handler
WindowsError: [Error 2] The system cannot find the file specified

In the registry, there is no HKEY_CURRENT_USER\Software\Classes\http.  I assume 
you 
meant HKEY_LOCAL_MACHINE?  The registry setting for 
HKEY_LOCAL_MACHINE\SOFTWARE\Classes\HTTP\shell\open\command is of type REG_SZ, 
and 
the value is "C:\Program Files\Internet Explorere\IEXPLORE.EXE" -nohome.

My web browser is IE version 7.0.5730.13.
```

Original comment by `ericback...@gmail.com` on 7 Dec 2009 at 6:22

**Comment by GoogleCodeExporter** [comment]
```
Sorry, there's a typo in my previous comment (and no way to edit comments once 
posted?).

The registry value is: "C:\Program Files\Internet Explorer\IEXPLORE.EXE" -nohome

And if I paste that registry value into a windows command prompt, it does 
successfully bring up an empty Internet Explorer window.
```

Original comment by `ericback...@gmail.com` on 7 Dec 2009 at 6:29

**Comment by GoogleCodeExporter** [comment]
```
I think I've resolved the primary issue in r401 -- I will now fail over to 
letting Windows 
launch the default HTML handler if I'm not able to launch the HTTP one. I've 
also added 
a bit of debug information.

There is still an outstanding bug in that the error window is not showing up on 
Windows. It looks like an issue with Tk & threading. I'm testing a workaround 
now for it.

```

Original comment by `tstromb...@google.com` on 7 Dec 2009 at 9:13
- Changed state: **Accepted**
- Added labels: **Priority-High**
- Removed labels: **Priority-Medium**

**Comment by GoogleCodeExporter** [comment]
```
r403 contains the remaining fix to make popups work again. This will be part of 
namebench 1.0.1. I will close the bug once it is available.

```

Original comment by `tstromb...@google.com` on 7 Dec 2009 at 11:31
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
I've uploaded namebench 1.0.1 - can anyone confirm whether or not this fixes 
the bug?

```

Original comment by `tstromb...@google.com` on 8 Dec 2009 at 1:59

**Comment by GoogleCodeExporter** [comment]
```
Nope.  1.0.1 does not fix neither the bug where the Unzip process hangs (but 
the 
applicaiton opens still), nor completing the production of the scan results. 
However, here is the contents of the log file that was produced once it failed.

Windows 7 Home Premium

After installing 1.0.1, I'm still experiencing the problem with the unzip 
process 
stalling. But now at the completion of the attempted scan, I get the following 
log 
file: 

Traceback (most recent call last): 

File "libnamebench\tk.pyc", line 87, in run 
File "libnamebench\base_ui.pyc", line 92, in RunBenchmark? 
File "libnamebench\base_ui.pyc", line 111, in DisplayHtmlReport? 
File "libnamebench\better_webbrowser.pyc", line 77, in open 
File "webbrowser.pyc", line 61, in open 
File "libnamebench\better_webbrowser.pyc", line 58, in open 
File "libnamebench\better_webbrowser.pyc", line 33, in create_win32_http_cmd 
WindowsError?: 2? The system cannot find the file specified 
```

Original comment by `Gary.Sch...@gmail.com` on 8 Dec 2009 at 6:18

**Comment by GoogleCodeExporter** [comment]
```
1.0.2 should fix this.

```

Original comment by `tstromb...@google.com` on 8 Dec 2009 at 7:43
- Changed state: **Fixed**
