### ISSUE TITLE
Client doesn't display results, stuck at "Using template path" message

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jeevandongre/namebench#28]
```
What steps will reproduce the problem?
1.Open namebench
2.Run Tests (I didn't change any of the default configs)
3.

What is the expected output? What do you see instead?

I was hoping that after running the tests I'd get all the results,
information, graphs, etc. But the program is stuck at the following status
message:
"Using template path "C:\Users\Username\AppData\Local\Temp\ckz_AA" I've
left it up and around for over an hour just to make sure it wasn't general
slowness and it never got past that.

What version of the product are you using? On what operating system?
Program Version: 0.96
OS: Windows 7 Home Premium x86

Please provide any additional information below.
I've even unplugged my router and connected my PC directly to the internet
and got the same problem.
```

Original issue reported on code.google.com by `thi.saa...@gmail.com` on 4 Dec 2009 at 12:56
- Merged into: #27

**Comment by GoogleCodeExporter** [comment]
```
Extracted this of your log:

Traceback (most recent call last):
  File "libnamebench\tk.pyc", line 57, in run
  File "libnamebench\base_ui.pyc", line 92, in RunBenchmark
  File "libnamebench\base_ui.pyc", line 103, in CreateReports
  File "libnamebench\benchmark.pyc", line 299, in CreateReport
  File "third_party\jinja2\environment.pyc", line 669, in render
  File "C:\Users\Thi\AppData\Local\Temp\ckz_AAD1\namebench\templates\html.tmpl", line
10, in top-level template code
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 5: ordinal 
not
in range(128)
```

Original comment by `thi.saa...@gmail.com` on 4 Dec 2009 at 12:59

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the report. There seems to be two bugs here:

* An error window did not pop up for this condition
* The nameserver data appears to include high-ASCII/unicode data which can't be 
piped through the templating 
system properly.

```

Original comment by `helixblue` on 4 Dec 2009 at 4:39

**Comment by GoogleCodeExporter** [comment]
Original comment by `tstromb...@google.com` on 4 Dec 2009 at 4:40
- Changed state: **Duplicate**
