### ISSUE TITLE
Windows: Hangs at "Checking connection quality" if Alexa Top Domains is selected

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jeevandongre/namebench#38]
```
What steps will reproduce the problem?
1. Launch Namebench 1.0 self-extracting exe
2. Run tests


What is the expected output? What do you see instead?

The application will freeze every time at some point without any result, 
and has to be terminated from Task Manager.


What version of the product are you using? On what operating system?

Version 0.96 and 1.0 on Windows 7 x64.


Please provide any additional information below.


The unzip routine does not come to an end, even after the main program has 
shown up.
```

Original issue reported on code.google.com by `ectomorp...@gmail.com` on 7 Dec 2009 at 8:57

**Comment by GoogleCodeExporter** [comment]
```
It's been tested under Win 7 x64 without problems, though I suspect this is 
related to:

http://code.google.com/p/namebench/issues/detail?id=27
http://code.google.com/p/namebench/issues/detail?id=30

Can you search your system to see if there is a namebench.exe.log file in your 
temporary files directory? If so, can you post the contents here?
```

Original comment by `tstromb...@google.com` on 7 Dec 2009 at 9:11

**Comment by GoogleCodeExporter** [comment]
```
Hi, here are the contents of this file:

Traceback (most recent call last):
  File "libnamebench\tk.pyc", line 55, in run
  File "libnamebench\base_ui.pyc", line 84, in PrepareBenchmark
  File "libnamebench\benchmark.pyc", line 74, in CreateTestsFromFile
IOError: [Errno 2] No such file or directory: 
'C:\\Users\\Giannino\\AppData\\Local\\Temp\\ckz_4KT8\\library.zip\\data/alexa-to
p-
10000-global.txt'


```

Original comment by `ectomorp...@gmail.com` on 7 Dec 2009 at 9:24

**Comment by GoogleCodeExporter** [comment]
```
Fantastic. Thanks for th

```

Original comment by `tstromb...@google.com` on 7 Dec 2009 at 9:38
- Changed title: *_Windows: Hangs at *_

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the bug report. I'm able to reproduce it! It looks like it's 
isolated to the Alexa 
Top Global Domains data source on Windows.  If you select another source such 
as a 
web browser history, it should work for you. A fix will be forthcoming.

```

Original comment by `tstromb...@google.com` on 7 Dec 2009 at 9:40
- Changed title: **Windows: Hangs at "Checking connection quality" if Alexa Top Domains is selected**
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
Ok, fine!
But the only benchmark source is Mozilla Firefox (while I don't even use it): 
isn't 
namebench mistaking somehow Chrome for Firefox?
```

Original comment by `ectomorp...@gmail.com` on 7 Dec 2009 at 10:08

**Comment by GoogleCodeExporter** [comment]
```
It sounds like namebench is not finding your chrome history file then. Do you 
mind 
pasting the path to the "History" file used by Chrome on your machine? On 
Windows, 
we currently try:

os.getenv('APPDATA', ''), 'Google', 'Chrome', 'User Data', 'Default', History'),
os.getenv('USERPROFILE', ''), 'Local Settings', 'Application Data',  'Google', 
'Chrome', 
'User Data', 'Default', 'History'),



```

Original comment by `tstromb...@google.com` on 7 Dec 2009 at 11:35

**Comment by GoogleCodeExporter** [comment]
```
Ok, the History files are right in:
C:\Users\[me]\AppData\Local\Google\Chrome\User Data\Default

They're in Default, there's no History folder.
```

Original comment by `ectomorp...@gmail.com` on 7 Dec 2009 at 11:42

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Is there a file named 'History' in the Default folder?

```

Original comment by `helixblue` on 8 Dec 2009 at 12:28

**Comment by GoogleCodeExporter** [comment]
```
Yup!
```

Original comment by `ectomorp...@gmail.com` on 8 Dec 2009 at 12:33

**Comment by GoogleCodeExporter** [comment]
```
I've uploaded namebench 1.0.1 - can you confirm whether or not this fixes the 
bug?

```

Original comment by `tstromb...@google.com` on 8 Dec 2009 at 1:59

**Comment by GoogleCodeExporter** [comment]
```
This fixed the bug for me.  Thanks.
```

Original comment by `Philosop...@gmail.com` on 8 Dec 2009 at 2:16

**Comment by GoogleCodeExporter** [comment]
Original comment by `tstromb...@google.com` on 8 Dec 2009 at 2:22
- Changed state: **Verified**
