### ISSUE TITLE
Windows: crash at startup - FixTk.py -> os.py: UnicodeEncodeError: 'ascii' codec can't encode character u'\xc1' in  position 12: ordinal not in range(12

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jeevandongre/namebench#41]
```
What steps will reproduce the problem?

1. Double click on the downloaded .exe

What is the expected output? What do you see instead?

An installing wizard of some sort, but I get an error message saying "See 
the logfile C:\Users\USUÁRIO\AppData\Local\Temp\ckz_VDN2\namebench.exe.log"

What version of the product are you using? On what operating system?

namebench-1.0.exe on Windows Vista Ultimate.

Please provide any additional information below.
The contents of the error log:

Traceback (most recent call last):
  File "namebench.py", line 61, in <module>
  File "Tkinter.pyc", line 38, in <module>
  File "FixTk.pyc", line 60, in <module>
  File "os.pyc", line 420, in __setitem__
UnicodeEncodeError: 'ascii' codec can't encode character u'\xc1' in 
position 12: ordinal not in range(128)
Traceback (most recent call last):
  File "namebench.py", line 61, in <module>
  File "Tkinter.pyc", line 38, in <module>
  File "FixTk.pyc", line 60, in <module>
  File "os.pyc", line 420, in __setitem__
UnicodeEncodeError: 'ascii' codec can't encode character u'\xc1' in 
position 12: ordinal not in range(128)

```

Original issue reported on code.google.com by `h.an...@gmail.com` on 8 Dec 2009 at 12:09

**Comment by GoogleCodeExporter** [comment]
Original comment by `tstromb...@google.com` on 8 Dec 2009 at 12:19
- Changed title: **Windows: crash at startup - FixTk.py -> os.py: UnicodeEncodeError: 'ascii' codec can't encode character u'\xc1' in  position 12: ordinal not in range(12**

**Comment by GoogleCodeExporter** [comment]
```
I hate Windows :(

```

Original comment by `tstromb...@google.com` on 8 Dec 2009 at 12:20
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
Looking at this, it seems that Python's TK library has problems with unicode 
paths. 
Does your username have an accent character in it (particularly A with a \ over 
it?)

```

Original comment by `tstromb...@google.com` on 8 Dec 2009 at 1:01
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
I have a similar error, except it's "position 13:"   My username does have an 
accent
over an 'a'- á. 
```

Original comment by `overdisp...@gmail.com` on 8 Dec 2009 at 3:19

**Comment by GoogleCodeExporter** [comment]
```
Same here. I have a ë in my user account name and I get the same thing.
```

Original comment by `dan...@289hq.com` on 8 Dec 2009 at 8:49

**Comment by GoogleCodeExporter** [comment]
```
WORKAROUND:

When starting the EXE, apply

-unzipDir X:\anywhere\
```

Original comment by `dan...@289hq.com` on 8 Dec 2009 at 8:53

**Comment by GoogleCodeExporter** [comment]
```
Thanks pwnadog, your solution works flawlessly :)
```

Original comment by `joze.pfeifer` on 8 Dec 2009 at 3:33

**Comment by GoogleCodeExporter** [comment]
```
I'm curious if 1.0.3 fixes this. If not, I am now posting zip file releases of 
namebench 
for Windows:

http://namebench.googlecode.com/files/namebench-for-windows-1.0.3.zip
```

Original comment by `thomas.r...@gmail.com` on 8 Dec 2009 at 5:49

**Comment by GoogleCodeExporter** [comment]
```
Thanks!  I was able to install and use the program successfully.  
```

Original comment by `overdisp...@gmail.com` on 8 Dec 2009 at 6:09

**Comment by GoogleCodeExporter** [comment]
```
Fixed in v1.0.4.

```

Original comment by `thomas.r...@gmail.com` on 10 Dec 2009 at 2:02
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Looks like this may still be an issue after all. Needs confirmation on Windows 
7.
```

Original comment by `tstromb...@google.com` on 10 Dec 2009 at 3:30
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
Issue 63 has been merged into this issue.
```

Original comment by `tstromb...@google.com` on 10 Dec 2009 at 3:30

**Comment by GoogleCodeExporter** [comment]
```
Partly workaround: Unzip it using 7zip to named folder. Move folder to Program 
Files. Program starts, but after pushing Start - shows the error message. See 
screenshot and log. 
```

Original comment by `maxgu...@gmail.com` on 10 Dec 2009 at 7:44

Attachments:
- [error.jpg](https://storage.googleapis.com/google-code-attachments/namebench/issue-41/comment-13/error.jpg)
- [namebench.exe.log](https://storage.googleapis.com/google-code-attachments/namebench/issue-41/comment-13/namebench.exe.log)

**Comment by GoogleCodeExporter** [comment]
```
DNS Benchmark by Precision Software is better. because its runs :)
```

Original comment by `maxgu...@gmail.com` on 10 Dec 2009 at 8:27

**Comment by GoogleCodeExporter** [comment]
```
1.0.4.1 fixes the FixTk.py error, tested under Windows 7 64-bit with an umlaut 
user. 
The remaining requirement was to add a TK_LIBRARY path.


```

Original comment by `thomas.r...@gmail.com` on 10 Dec 2009 at 11:11
- Changed state: **Fixed**
