### ISSUE TITLE
Error when writing results:  File "Tkinter.pyc", line 1378, in event_generate

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jeevandongre/namebench#47]
```
What steps will reproduce the problem?
1. Ran with defaults



What is the expected output? What do you see instead?
When the test finished and results were being written got the following error:
---------------------------
expected boolean value but got "??"
---------------------------
  File "libnamebench\base_ui.pyc", line 46, in UpdateStatus

  File "libnamebench\tk.pyc", line 80, in msg

  File "libnamebench\tk.pyc", line 48, in AddMsg

  File "Tkinter.pyc", line 1378, in event_generate

---------------------------
OK   
---------------------------



What version of the product are you using? On what operating system?
Downloaded it today, so latest I guess. Nothing on program UI to say which
version.

Running on Windows 7 Home Premium 64bit

```

Original issue reported on code.google.com by `mikewill...@gmail.com` on 8 Dec 2009 at 5:31

**Comment by GoogleCodeExporter** [comment]
```
I'm not sure what to make of this error. Can you see if the newly uploaded 
1.0.2 version 
has the same issue?

```

Original comment by `tstromb...@google.com` on 8 Dec 2009 at 7:33
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
Original comment by `tstromb...@google.com` on 8 Dec 2009 at 7:36
- Changed title: **Error when writing results:  File "Tkinter.pyc", line 1378, in event_generate**

**Comment by GoogleCodeExporter** [comment]
```
I am also getting this with 1.0.2.  Same error as the OP.

expected boolean value but got "??"
  File "libnamebench\base_ui.pyc", line 46, in UpdateStatus
  File "libnamebench\tk.pyc", line 81, in msg
  File "libnamebench\tk.pyc", line 49, in AddMsg
  File "Tkinter.pyc", line 1378, in event_generate

I am also 64-bit on Win2k8.
```

Original comment by `glack...@gmail.com` on 8 Dec 2009 at 10:30

**Comment by GoogleCodeExporter** [comment]
```
Not sure if it helps, but here is the more complete stack track from the log 
file:

Traceback (most recent call last):
  File "libnamebench\tk.pyc", line 86, in run
  File "libnamebench\base_ui.pyc", line 73, in PrepareBenchmark
  File "libnamebench\base_ui.pyc", line 46, in UpdateStatus
  File "libnamebench\tk.pyc", line 81, in msg
  File "libnamebench\tk.pyc", line 49, in AddMsg
  File "Tkinter.pyc", line 1378, in event_generate
TclError: expected boolean value but got "??"

Clicking "Start Benchmark" a second time allowed it to complete with no errors. 
Entering new DNS servers and clicking "Start Benchmark" a third time eventually
failed with another error:

Traceback (most recent call last):
  File "libnamebench\tk.pyc", line 88, in run
  File "libnamebench\base_ui.pyc", line 91, in RunBenchmark
  File "libnamebench\base_ui.pyc", line 107, in CreateReports
  File "libnamebench\base_ui.pyc", line 46, in UpdateStatus
  File "libnamebench\tk.pyc", line 81, in msg
  File "libnamebench\tk.pyc", line 49, in AddMsg
  File "Tkinter.pyc", line 1378, in event_generate
TclError: invalid command name ""[45760024MessageHandler 3603 ?? ?? ?? ?? 0 0 
?? 0 0
?? 0 ?? ?? . 35 -1 -1 ??]" == "break""

A fourth run with the same DNS servers from attempt #3 completed successfully 
with no
errors.
```

Original comment by `glack...@gmail.com` on 8 Dec 2009 at 10:50

**Comment by GoogleCodeExporter** [comment]
```
I was not able to replicate this on Windows 7 64-bit Home Premium, but I did 
put in 
a hacky bandaid for this error. Can someone who experienced this issue try this 
debug build of namebench:

http://namebench.googlecode.com/files/namebench-1.0.2-test-issue-47.exe

It patches my code so that if event_generate() fails for whatever reason, it 
simply 
ignores the status update and catches it on the next cycle. This appears to be 
a 
thread-safety issue with the Tk libraries, so I'm just masking it for now. I 
have a 
feeling this is not the only place I will be seeing this issue.


```

Original comment by `tstromb...@google.com` on 8 Dec 2009 at 3:52
- Changed state: **Started**
- Added labels: **Priority-High**
- Removed labels: **Priority-Medium**

**Comment by GoogleCodeExporter** [comment]
```
While there may be other thread safety issues with Tk, I believe this one has 
been fixed 
by version 1.0.3. Please let me know if this is not the case.

```

Original comment by `thomas.r...@gmail.com` on 8 Dec 2009 at 5:45
- Changed state: **Fixed**
