### ISSUE TITLE
OpenSUSE 11.2: TclError: out of stack space (infinite loop?)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jeevandongre/namebench#52]
```
What steps will reproduce the problem?
1. ./namebench.py
2. Start Benchmark

What is the expected output? What do you see instead?
I was expecting some pretty graphs or something.  Instead the GUI doesn't
change and the following is output to the console:
[psy@sable:~/src/namebench-1.0.2]$ ./namebench.py
> Searching for usable data sources
- History: /home/psy/.mozilla/firefox/9pq9jgte.default/places.sqlite
- History: /home/psy/.opera/global_history.dat
- 593 records read in 0.032016992569s
> All available sources have been parsed.
> Running...
> Ready
> Matching "Mozilla Firefox (576)" to [('firefox', 'Mozilla Firefox', 576),
('opera', 'Opera', 17), (None, 'Alexa Top Global Domains', 10000)]
> Parsed source type to firefox
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/threading.py", line 525, in __bootstrap_inner
    self.run()
  File "/home/psy/src/namebench-1.0.2/libnamebench/tk.py", line 84, in run
    self.msg('Started thread', enable_button=False)
  File "/home/psy/src/namebench-1.0.2/libnamebench/tk.py", line 81, in msg
    return AddMsg(message, master=self.master, **kwargs)
  File "/home/psy/src/namebench-1.0.2/libnamebench/tk.py", line 49, in AddMsg
    master.event_generate('<<msg>>', when='tail')
  File "/usr/lib64/python2.6/lib-tk/Tkinter.py", line 1378, in event_generate
    self.tk.call(args)
TclError: out of stack space (infinite loop?)

Au revoir, mes amis!
[psy@sable:~/src/namebench-1.0.2]$


What version of the product are you using? On what operating system?
namebench-1.0.2 on openSUSE 11.2 for x86-64


```

Original issue reported on code.google.com by `tristan.miller@nothingisreal.com` on 8 Dec 2009 at 11:33

**Comment by GoogleCodeExporter** [comment]
```
I bet this is due to a version of Tk being installed that is not thread-safe, 
though I had 
assumed that using the event_generate call would have avoided this. I'll take a 
look at it 
today.

```

Original comment by `tstromb...@google.com` on 8 Dec 2009 at 1:44
- Changed title: **OpenSUSE 11.2: TclError: out of stack space (infinite loop?)**
- Changed state: **Started**
- Added labels: **Priority-High**
- Removed labels: **Priority-Medium**

**Comment by GoogleCodeExporter** [comment]
```
This issue was closed by revision r452.
```

Original comment by `thomas.r...@gmail.com` on 8 Dec 2009 at 8:44
- Changed state: **Fixed**
