### ISSUE TITLE
Windows 7: _SecondaryCachePath IndexError: list index out of range 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jeevandongre/namebench#56]
```
What steps will reproduce the problem?
1.
2.
3.

What is the expected output? What do you see instead?
Traceback (most recent call last):
  File "libnamebench\tk.pyc", line 86, in run
  File "libnamebench\base_ui.pyc", line 67, in PrepareBenchmark
  File "libnamebench\nameserver_list.pyc", line 279, in CheckHealth
  File "libnamebench\nameserver_list.pyc", line 309, in _SecondaryCachePath
IndexError: list index out of range

What version of the product are you using? On what operating system?
on windows 7 ultimate 32bit

Please provide any additional information below.


```

Original issue reported on code.google.com by `kikok...@gmail.com` on 8 Dec 2009 at 3:22

**Comment by GoogleCodeExporter** [comment]
```
It looks like it can't get a list of valid nameservers on your machine. Can you 
see if this 
debug build has the same issue? It should at least fall back to listing 
127.0.0.1 instead 
of crashing outright.

http://namebench.googlecode.com/files/namebench-1.0.2-test-issue-47.exe
```

Original comment by `tstromb...@google.com` on 8 Dec 2009 at 3:55
- Changed title: *_Windows 7: _SecondaryCachePath IndexError: list index out of range *_
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
As far as I know, 1.0.3 includes a fix for this. Please let me know if this is 
not the case.

```

Original comment by `thomas.r...@gmail.com` on 8 Dec 2009 at 5:45
- Changed state: **Fixed**
