### ISSUE TITLE
Windows 7: "Errors occurred" when users with unicode characters close namebench 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jeevandongre/namebench#65]
```
What steps will reproduce the problem?
1. Have an umlaut in your username
2. Run namebench
3. Close it when you are done

What is the expected output? What do you see instead?

Nothing. No errors

Traceback:

Traceback (most recent call last):
  File "libnamebench\better_webbrowser.pyc", line 91, in open
  File "subprocess.pyc", line 621, in __init__
  File "subprocess.pyc", line 830, in _execute_child
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 
12: ordinal not in range(128)

--------------------------------------------------------
The weird thing is, that we do everything we can at the moment to catch 
these exceptions. Even putting webbrowser.open in a thread does not 
defeat this issue.

```

Original issue reported on code.google.com by `tstromb...@google.com` on 11 Dec 2009 at 11:41

**Comment by GoogleCodeExporter** [comment]
```
I believe this was fixed in version 1.2.

```

Original comment by `tstromb...@google.com` on 2 Mar 2010 at 2:54
- Changed state: **Fixed**
