### ISSUE TITLE
Support for IPv6

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jeevandongre/namebench#66]
```
What steps will reproduce the problem?
1. In the nameservers box enter one or more IPv6 addresses.
2. Press "Start Benchmark"

What is the expected output? What do you see instead?
The benchmark should start running but instead it says that no nameservers
were found.

What version of the product are you using? On what operating system?
namebench-1.0.5 on Windows XP SP3

Please provide any additional information below.


```

Original issue reported on code.google.com by `chaz6....@gmail.com` on 12 Dec 2009 at 2:18

**Comment by GoogleCodeExporter** [comment]
```
I won't have an easily available IPV6 capable host to play with until tomorrow, 
but 
revision 488 should parse and make use of IPV6 addresses (tested on 
command-line, 
should work for all interfaces). If you get bored, check namebench out from 
subversion and give it a spin. 

So far I'm assuming that all of the underlying libraries should work. dnspython 
at 
least seems to treat it properly:

* Error with 1:200:0:8002:203:47ff:fea5:3085 [1:200:0:8002:203:47ff:fea5:3085]: 
<class 'socket.error'> ((101, 'Network is unreachable'))

```

Original comment by `tstromb...@google.com` on 14 Dec 2009 at 5:24
- Changed state: **Started**
- Added labels: **Type-Enhancement**
- Removed labels: **Type-Defect**

**Comment by GoogleCodeExporter** [comment]
```
I made a typo above. The fix is actually in revision 489

```

Original comment by `tstromb...@google.com` on 14 Dec 2009 at 5:25

**Comment by GoogleCodeExporter** [comment]
```
Unfortunately this does not appear to work with r489:-

$ python namebench.py -O 2001:470:20::2,2001:4f8:3:2bc:1::64:20
namebench 1.0.5 - data/alexa-top-10000-global.txt (weighted) on 2009-12-14
18:28:31.256315
threads=40 tests=200 runs=1 timeout=2.0 health_timeout=4.0 servers=10
------------------------------------------------------------------------------
- Checking connection quality...
- Connection appears healthy (latency 59.36ms)
- Building initial DNS cache for 2 nameservers [40 threads]
- Waiting for health check threads for 2 servers: 0/2..2/2
.Traceback (most recent call last):
  File "namebench.py", line 78, in <module>
    namebench.Execute()
  File "/tmp/namebench-read-only/libnamebench/cli.py", line 135, in Execute
    nameservers = self.PrepareNameservers()
  File "/tmp/namebench-read-only/libnamebench/cli.py", line 93, in PrepareNameservers
    nameservers.CheckHealth()
  File "/tmp/namebench-read-only/libnamebench/nameserver_list.py", line 291, in
CheckHealth
    self.RunHealthCheckThreads()
  File "/tmp/namebench-read-only/libnamebench/nameserver_list.py", line 450, in
RunHealthCheckThreads
    raise TooFewNameservers('None of the %s nameservers tested are healthy' % len(self))
libnamebench.nameserver_list.TooFewNameservers: 'None of the 2 nameservers 
tested are
healthy'

```

Original comment by `maken...@gmail.com` on 14 Dec 2009 at 5:29

**Comment by GoogleCodeExporter** [comment]
```
This was fixed for me in r509 - do you mind checking out the subversion tree to 
see?


```

Original comment by `thomas.r...@gmail.com` on 2 Jan 2010 at 11:58
- Changed state: **Fixed**
