### ISSUE TITLE
TypeError: stat() argument 1 must be encoded string without NULL bytes, not str

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jeevandongre/namebench#87]
```
What steps will reproduce the problem?
1.download
2.run
3.click on "start benchmark"

What is the expected output? What do you see instead?

Instead of benchmark results I get a window saying :
File "libnamebench\base_ui.pyc", line 67, in PrepareBenchmark
File "libnamebench\nameserver_list.pyc", line 280, in CheckHealth
File "libnamebench\nameserver_list.pyc", line 234, in InvokeSecondaryCache
File "libnamebench\nameserver_list.pyc", line 321, in _LoadSecondaryCache
File "genericpath.pyc", line 18, in exists

What version of the product are you using? On what operating system?
namebench 1.0.5 on windows xp sp3

Please provide any additional information below.
namebench.exe.log says :
Traceback (most recent call last):
  File "libnamebench\tk.pyc", line 101, in run
  File "libnamebench\base_ui.pyc", line 67, in PrepareBenchmark
  File "libnamebench\nameserver_list.pyc", line 280, in CheckHealth
  File "libnamebench\nameserver_list.pyc", line 234, in 
InvokeSecondaryCache
  File "libnamebench\nameserver_list.pyc", line 321, in _LoadSecondaryCache
  File "genericpath.pyc", line 18, in exists
TypeError: stat() argument 1 must be encoded string without NULL bytes, 
not str

```

Original issue reported on code.google.com by `woyta...@gmail.com` on 3 Jan 2010 at 10:43

**Comment by GoogleCodeExporter** [comment]
```
I forgot to say that the older version of namebench works fine for me(1.0.3)
```

Original comment by `woyta...@gmail.com` on 3 Jan 2010 at 10:45

**Comment by GoogleCodeExporter** [comment]
```
I haven't a clue of why this is happening yet -- do you mind seeing if 
namebench 
1.1b1 has the same problem? I suspect it will, but I'd rather not chase after 
the issue 
if it's been fixed already. 

If it's still broken, I'll compile a debug build that should display where the 
problem 
may lie.

By the way - What was the last status message in the window?


```

Original comment by `thomas.r...@gmail.com` on 3 Jan 2010 at 11:16
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
namebench 1.1b1 has the same bug, but the line numbers are different then 1.0.5
File "libnamebench\tk.pyc", line 102, in run
File "libnamebench\base_ui.pyc", line 80, in PrepareNameServers
File "libnamebench\nameserver_list.pyc", line 303, in CheckHealth
File "libnamebench\nameserver_list.pyc", line 236, in InvokeSecondaryCache
File "libnamebench\nameserver_list.pyc", line 380, in _LoadSecondaryCache
File "genericpath.pyc", line 18, in exists
TypeError: stat() argument 1 must be encoded string without NULL bytes, not str

Last status message in the window just before the error message pop up is: 
Checking 
nameserver health
```

Original comment by `woyta...@gmail.com` on 4 Jan 2010 at 6:15

**Comment by GoogleCodeExporter** [comment]
```
I believe this error has to do with the encoding of the temporary path. As of 
r578 - I have made this function 
more resilient to failure, but I suspect you will run into issues further on 
when it comes time to display the web 
page. I will post another namebench 1.1 beta tonight, and will see if it fixes 
this.
```

Original comment by `tstromb...@google.com` on 4 Jan 2010 at 6:57
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
Do you mind trying again in namebench 1.1?

```

Original comment by `thomas.r...@gmail.com` on 4 Jan 2010 at 10:21

**Comment by GoogleCodeExporter** [comment]
```
namebench 1.1 works fine, thanks and keep up the good work.
```

Original comment by `woyta...@gmail.com` on 5 Jan 2010 at 1:30

**Comment by GoogleCodeExporter** [comment]
Original comment by `tstromb...@google.com` on 5 Jan 2010 at 3:18
- Changed state: **Fixed**
